### ISSUE TITLE
Commission Dashboard

### ISSUE THREAD

**Issue by zkat** [digitalworkersguild/banchan#107]
* [x] List commissions
* [x] Filter/search commissions by various characteristics (tag, title, keywords)

**Comment by skullbunnygalaxy** [comment]
Right now #106 and #107 are handled on the same page. Leaving open as separate issues to handle the different use cases for the same page. May merge into one issue later.

**Comment by zkat** [comment]
making this a generalized dashboard

**Comment by zkat** [comment]
This is done!
