### ISSUE TITLE
Switching from Bulma

### ISSUE THREAD

**Issue by zkat** [digitalworkersguild/banchan#61]
Perhaps to TailwindCSS?

Let's explore what this is actually gonna be like and how much more work it'll put in our hands.

**Comment by skullbunnygalaxy** [comment]
Outlining steps that we have pinpointed so far:
- [ ] migrate to esbuild
- [ ] remove bulma & its dependencies
- [ ] add tailwindcss
- [ ] pinpoint areas with bulma specific code to rewrite with tailwind CSS, ie `lib/banchan_web/components/card.ex`

**Comment by skullbunnygalaxy** [comment]
Installed [tailwindcss-forms](https://github.com/tailwindlabs/tailwindcss-forms) plugin for basic styling.

More pieces to restyle at some point to create better looking forms:
- [ ] login_live.ex
- [ ] register_live.ex
- [ ] reset_password_live.ex
- [ ] studio_live/edit.ex

**Comment by skullbunnygalaxy** [comment]
Note: need to fix font awesome icons in nav.ex
