### ISSUE TITLE
Fix broken test ` require_authenticated_user/2 stores the path to redirect to on GET (BanchanWeb.UserAuthTest)`

### ISSUE THREAD

**Issue by zkat** [digitalworkersguild/banchan#63]

**Comment by skullbunnygalaxy** [comment]
The failing auth test checks to see if a path is stored to redirect the user if they are not authenticated. Looks like it broke either with the upgrade to phoenix 1.6 (tests failed to run due to CI getting canceled) or on the merge after that (where it is def failing).
