### ISSUE TITLE
Implement TailwindCSS responsive design

### ISSUE THREAD

**Issue by skullbunnygalaxy** [digitalworkersguild/banchan#75]
When removing Bulma assets and replacing it with TailwindCSS, we focused on basic functionality, and in the process that meant that for the most part responsive design is no longer working on the app. Need to test phone, tablet, and desktop views, including widescreen desktop view, and implement responsive design using TailwindCSS.

**Comment by zkat** [comment]
This is all done. We can improve individual things that we find along the way.
