### ISSUE TITLE
Studio Discovery

### ISSUE THREAD

**Issue by zkat** [digitalworkersguild/banchan#99]
We need search functionality to allow users to find studios by keyword, tag, and artist.

**Comment by shibaobun** [comment]
so from conversations on discord, it seems like the current plan is to have tags and categories be global, with categories being system/admin-level entities with descriptions, and tags being user-level entities.
in the future, this will probably mean a future ticket for an admin dashboard where categories can be added/removed/renamed n stuffs

**Comment by shibaobun** [comment]
also, categories will be browseable, while tags will just be queryable/informative

**Comment by shibaobun** [comment]
we're ditching categories, and just adding tags as string arrays :+1:
